# @server = http://192.168.100.36:5900
@server = http://192.168.100.36:5900
@id = {{createMaquina.response.body.$.id}}

# @createdHostId = {{createHost.response.body.$.id}}
# @createdUserId = {{createdUser.response.body.$.id}}
@token = {{singin.response.body.$.token}}

### cadastrarMaquina
# @name createMaquina
POST {{server}}/maquinas
Content-Type: application/json

{
    "nome": "teste1",
    "so": "windows"
}


### pegarStatus
GET {{server}}/maquinas

### pegarStatusMaquina
GET {{server}}/maquinas?id={{id}}

### pegarStatusMaquina2
GET {{server}}/maquinas/{{id}}

### atualizarMaquina
PUT {{server}}/maquinas/{{id}}
Content-Type: application/json

{
    "cputot": "3.7",
    "cpudet": "7.1;0.0;8.0;2.0;4.9;3.0;1.0;2.0",
    "cputmp": "53",
    "memtot": "7.44",
    "memusa": "4.13",
    "swptot": "12",
    "swpusa": "0.02",
    "dsktot": "233.18",
    "dskusa": "107.22",
    "dsktmp": "31.85"
}

### Deletar Maquina
DELETE {{server}}/maquinas/{{id}}
Authorization: bearer {{token}}

### Criar Usuario
POST {{server}}/usuarios
Content-Type: application/json

{
    "nome": "João Weslley",
    "username": "joaoweslley",
    "email": "joao@localhost",
    "senha": "12345678"
}

### Checa Usuarios
GET {{server}}/usuarios/

### Deleta Usuarios
DELETE {{server}}/usuarios/3
Authorization: bearer {{token}}


### Realizar login
# @name singin
POST {{server}}/singin
Content-Type: application/json

{
    "email": "joao@localhost",
    "senha": "12345678"
}

### Realizar login 2
# @name singin
POST {{server}}/singin
Content-Type: application/json

{
    "username": "joaoweslley",
    "senha": "12345678"
}

### Realizar login admin
# @name singin
POST {{server}}/singin
Content-Type: application/json

{
    "username": "admin",
    "senha": "admin"
}